
artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  kaggle_URL: https://www.kaggle.com/datasets/muhammadmaazsayyed/plant-disease-balanced/download?datasetVersionNumber=1
  kaggle_file: artifacts/data_ingestion/plant-disease-balanced.zip
  

base_model:
  root_dir: artifacts/base_model
  base_model_path: artifacts/base_model/base_model.h5
  updated_model_path: artifacts/base_model/updated_model.h5






